# Generated by Django 4.2.3 on 2023-08-06 08:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=64)),
                ('video', models.FileField(upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'mp4', 'webm', 'mkv'])])),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.chanel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=64)),
                ('photo', models.ImageField(upload_to='photos_uploaded')),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.chanel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
