# Generated by Django 4.2.3 on 2023-08-06 19:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0002_text_remove_video_chanel_delete_photo_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='currentProfit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chanel',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='chanel',
            name='subscriptionPrice1',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chanel',
            name='subscriptionPrice2',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chanel',
            name='subscriptionPrice3',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chanel',
            name='subscriptionPrice4',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='pro',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=64)),
                ('pro', models.BooleanField(default=False)),
                ('video', models.FileField(upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['avi', 'mp4', 'webm', 'mkv'])])),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.chanel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.SmallIntegerField()),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.chanel')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('summary', models.CharField(max_length=64)),
                ('pro', models.BooleanField(default=False)),
                ('photo', models.ImageField(upload_to='photos_uploaded')),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.chanel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
