# Generated by Django 4.2.3 on 2023-08-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0003_chanel_currentprofit_chanel_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
