# Generated by Django 4.2.3 on 2023-08-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0004_photo_price_text_price_video_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text',
            field=models.TextField(blank=True, max_length=512, null=True),
        ),
    ]
