# Generated by Django 4.2.3 on 2023-08-10 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0005_alter_text_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
