# Generated by Django 4.2.3 on 2023-08-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0006_delete_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanel',
            name='subscriptionPrice1',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='subscriptionPrice2',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='subscriptionPrice3',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='chanel',
            name='subscriptionPrice4',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
