# Generated by Django 4.2.3 on 2023-08-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='profit',
            field=models.SmallIntegerField(null=True),
        ),
    ]
