# Generated by Django 4.2.3 on 2023-08-10 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0006_delete_subscription'),
        ('creation', '0002_owner_profit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remaining', models.SmallIntegerField()),
                ('chanel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumption.chanel')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creation.member')),
            ],
        ),
    ]
