# Generated by Django 4.2.3 on 2023-08-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0003_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subType',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
