# Generated by Django 4.2.3 on 2023-08-22 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creation', '0004_subscription_subtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subType',
            field=models.CharField(default='1', max_length=2),
        ),
    ]
